name: 'Replicated KOTS release'
description: 'Create a Replicated KOTS release on a channel'
inputs:
  replicated-app:
    description: 'Replicated App Slug'
    required: true
    default: 'my-app-enterprise'
  replicated-api-token:
    description: 'Replicated API Token'
    required: true
    default: ''
  yaml-dir:
    description: 'Directory containing KOTS application manifests'
    required: true
    default: 'manifests'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '/replicated release create --promote=${GITHUB_REF} --ensure-channel --yaml-dir=${{ inputs.yaml-dir }} --release-notes="GitHub Action release of ${GITHUB_REF} triggered by ${GITHUB_ACTOR}: [${GITHUB_SHA::7}](https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})" --version=${GITHUB_SHA::7}'
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}
